"""Generate the OpenRewrite invocation for a plan and run it.

Maven projects run the real ``rewrite-maven-plugin`` goal directly against
the project's own pom.xml -- no generated project files needed. Gradle
projects use a throwaway Gradle *init script* (OpenRewrite's documented way
to apply the plugin without touching the project's own build files), deleted
again once the run finishes.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import stat
import subprocess
from pathlib import Path

from . import recipes as R
from .discover import BuildRoot
from .errors import ModError

SOURCE_BUILD_CACHE = Path(os.environ.get("JAVAMOD_CACHE_DIR", Path.home() / ".cache/javamod")) / "recipe-builds"


def _write_recipe_file(path: Path, phases: list[R.MigrationPhase]) -> str:
    name = "dev.javamod.Migration"
    recipe_list = "\n".join(f"  - {item}" for phase in phases for item in phase.recipes)
    path.write_text(
        "---\ntype: specs.openrewrite.org/v1beta/recipe\n"
        f"name: {name}\ndisplayName: javamod migration\n"
        f"description: Generated by javamod for a single run.\nrecipeList:\n{recipe_list}\n",
        encoding="utf-8",
    )
    return name


def _executable(build: BuildRoot) -> str:
    # Deliberately the system mvn/gradle, never the project's own wrapper.
    # The wrapper pins whatever Maven/Gradle the project last committed to
    # (some are a decade old) and may not even understand flags this process
    # passes, let alone resolve a modern OpenRewrite plugin. Validating the
    # migrated build with the project's *own* toolchain still matters -- that
    # happens in buildcheck.py, which does use the wrapper.
    return "mvn" if build.tool == "maven" else "gradle"


def ensure_source_recipes_built(modules: list[str], log) -> Path:
    """Build each module straight from the OpenRewrite GitHub repo into mavenLocal.

    Returns the local Maven repository path (mavenLocal's default,
    ``~/.m2/repository``) so callers can point Gradle/Maven at it first.
    """
    local_repo = Path.home() / ".m2" / "repository"
    for module in modules:
        version = R.MAVEN_CENTRAL_VERSIONS[module]
        marker = SOURCE_BUILD_CACHE / f"{module}-{version}.ok"
        if marker.exists():
            continue
        repo_url = f"https://github.com/{R.SOURCE_REPOS[module]}.git"
        checkout = SOURCE_BUILD_CACHE / f"{module}-{version}"
        if checkout.exists():
            shutil.rmtree(checkout)
        log(f"building {module} {version} from source ({repo_url})")
        _run(["git", "clone", "--depth", "1", "--branch", f"v{version}", repo_url, str(checkout)],
             cwd=SOURCE_BUILD_CACHE.parent)
        gradlew = checkout / "gradlew"
        if gradlew.is_file():
            gradlew.chmod(gradlew.stat().st_mode | stat.S_IXUSR)
        _run([str(gradlew) if gradlew.is_file() else "gradle", "--no-daemon", "-q", "publishToMavenLocal"],
             cwd=checkout, timeout=1800)
        marker.parent.mkdir(parents=True, exist_ok=True)
        marker.write_text("ok\n", encoding="utf-8")
    return local_repo


def _run(cmd: list[str], cwd: Path, timeout: int = 900) -> None:
    cwd.mkdir(parents=True, exist_ok=True)
    try:
        completed = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                    text=True, timeout=timeout, check=False)
    except FileNotFoundError as exc:
        raise ModError(f"command not found: {cmd[0]}") from exc
    except subprocess.TimeoutExpired as exc:
        raise ModError(f"timed out: {' '.join(cmd)}") from exc
    if completed.returncode != 0:
        raise ModError(f"command failed ({completed.returncode}): {' '.join(cmd)}\n{completed.stdout[-4000:]}")


def _maven_settings(path: Path, repo_url: str, username_env: str, token_env: str) -> None:
    path.write_text(f"""<settings>
  <servers>
    <server><id>javamod-recipes</id>
      <username>${{env.{username_env}}}</username>
      <password>${{env.{token_env}}}</password>
    </server>
  </servers>
  <profiles>
    <profile><id>javamod-recipes</id>
      <repositories>
        <repository><id>javamod-recipes</id><url>{repo_url}</url></repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository><id>javamod-recipes</id><url>{repo_url}</url></pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
  <activeProfiles><activeProfile>javamod-recipes</activeProfile></activeProfiles>
</settings>
""", encoding="utf-8")


def _gradle_init(path: Path, recipe_name: str, recipe_file: Path, gradle_plugin_version: str,
                  artifacts: list[str], local_repo: Path | None, codegenome_creds: tuple[str, str] | None) -> None:
    repos = []
    if local_repo is not None:
        repos.append(f'mavenLocal {{ url = uri({json.dumps(local_repo.as_uri())}) }}')
    if codegenome_creds:
        username_env, token_env = codegenome_creds
        repos.append(
            f'maven {{ url = uri({json.dumps(R.CODEGENOME_URL)}); '
            f'credentials {{ username = System.getenv({json.dumps(username_env)}); '
            f'password = System.getenv({json.dumps(token_env)}) }} }}'
        )
    repos.append("mavenCentral()")
    repo_block = "\n        ".join(repos)
    deps = "\n        ".join(f'rewrite("{a}")' for a in artifacts)
    path.write_text(f"""initscript {{
    repositories {{
        {repo_block}
        maven {{ url = uri("https://plugins.gradle.org/m2") }}
    }}
    dependencies {{ classpath("org.openrewrite:plugin:{gradle_plugin_version}") }}
}}
rootProject {{
    plugins.apply(org.openrewrite.gradle.RewritePlugin)
    dependencies {{
        {deps}
    }}
    rewrite {{
        activeRecipe({json.dumps(recipe_name)})
        configFile = file({json.dumps(str(recipe_file))})
    }}
    afterEvaluate {{ repositories {{ {repo_block} }} }}
}}
""", encoding="utf-8")


def run(build: BuildRoot, plan: R.Plan, *, recipe_source: str, allow_codegenome: bool,
        codegenome_username_env: str = "CODE_GENOME_USERNAME", codegenome_token_env: str = "CODE_GENOME_TOKEN",
        log=print) -> bool:
    """Apply *plan* to *build* in place. Returns True if anything changed."""
    if not plan.phases:
        return False
    artifacts = R.resolve_artifacts(plan.modules, recipe_source, allow_codegenome)
    plugin_version = R.PLUGIN_VERSIONS[recipe_source][build.tool]
    workdir = build.path / ".javamod-openrewrite"
    workdir.mkdir(exist_ok=True)
    try:
        recipe_name = _write_recipe_file(workdir / "recipe.yml", plan.phases)
        local_repo = ensure_source_recipes_built(plan.modules, log) if recipe_source == "source" else None
        exe = _executable(build)
        if build.tool == "maven":
            cmd = [exe, "--batch-mode", "--no-transfer-progress", "-U",
                   f"org.openrewrite.maven:rewrite-maven-plugin:{plugin_version}:run",
                   f"-Drewrite.recipeArtifactCoordinates={','.join(artifacts)}",
                   f"-Drewrite.activeRecipes={recipe_name}",
                   f"-Drewrite.configLocation={workdir / 'recipe.yml'}"]
            if recipe_source == "codegenome":
                _maven_settings(workdir / "settings.xml", R.CODEGENOME_URL,
                                 codegenome_username_env, codegenome_token_env)
                cmd[1:1] = ["-s", str(workdir / "settings.xml")]
        else:
            codegenome_creds = (codegenome_username_env, codegenome_token_env) if recipe_source == "codegenome" else None
            _gradle_init(workdir / "init.gradle", recipe_name, workdir / "recipe.yml", plugin_version,
                         artifacts, local_repo, codegenome_creds)
            cmd = [exe, "--no-daemon", "--init-script", str(workdir / "init.gradle"), "rewriteRun"]
        log(f"running OpenRewrite ({build.tool}, {len(plan.recipe_names)} recipes)...")
        _run(cmd, cwd=build.path, timeout=1800)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)
    return _has_changes(build.path)


def _has_changes(path: Path) -> bool:
    # gitrepo.clone_source always leaves *path* inside a git work tree (it
    # `git init`s even a plain, non-git source directory), so a plain
    # status check from anywhere under the build root is enough.
    completed = subprocess.run(["git", "status", "--porcelain"], cwd=path, stdout=subprocess.PIPE, text=True)
    return bool(completed.stdout.strip())
